print("========================================")
print(" MI PRIMER REPOSITORIO EN GIT Y GITHUB")
print("========================================")
print("Nombre: Gonzalo Richard Gutierrez Gutierrez")
print("Nombre: Fernando Luis Angel Arias Cayujra")
print("Carrera: Ingeniería de Sistemas")
print("Semestre: Primero")
print("Estoy aprendiendo Git y GitHub")
print("Deseamos aprender sobre POO")
print("Me encanta la programación y quiero aprender mucho más sobre ello")
print("Me interesa aprender Git y GitHub para poder organizar mejor mis códigos y proyectos")